#!/bin/bash
#
# Start-Stop-Hooks for component SmartGazeboBaseServer
#
# This script provides methods to call custom commands pre/post of
# starting/stoping the component during launch on the device.
# This script is being executed on the target device where this 
# component is running.
#

#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# This file is generated once. Modify this file to your needs. 
# If you want the toolchain to re-generate this file, please 
# delete it before running the code generator.
#--------------------------------------------------------------------------

case "$1" in

pre-start)
	# first, trigger hooks as delivered from component ...
	bash startstop-hooks-component-SmartGazeboBaseServer.sh pre-start
	
	# ...then call user/deployment specific hook:
	echo "Triggering pre-start hooks ..."

#	bash $SMART_ROOT_ACE/repos/DataRepository/gazebo/startGazebo.sh worlds/pioneerOffice.world

        FROM=$(pwd)
        DEPL_GAZEBO_FILES=$FROM/gazebo

        export GAZEBO_RESOURCE_PATH=/usr/share/gazebo-9/
        export GAZEBO_RESOURCE_PATH=$GAZEBO_RESOURCE_PATH:../
        export GAZEBO_MODEL_PATH=:$DEPL_GAZEBO_FILES/models
        export GAZEBO_PLUGIN_PATH=$SMART_ROOT_ACE/lib
        echo "GAZEBO_RESOURCE_PATH: $GAZEBO_RESOURCE_PATH"
        echo "GAZEBO_MODEL_PATH: $GAZEBO_MODEL_PATH"
        echo "GAZEBO_PLUGIN_PATH: $GAZEBO_PLUGIN_PATH"        
        xterm -title "Gazebo Terminal" -e "echo ""Before""; export SVGA_VGPU10=0;pwd; ""echo ""SVGA_VGPU10: $SVGA_VGPU10"";gazebo --verbose $DEPL_GAZEBO_FILES/worlds/pioneerOffice.world || bash; sleep 5" &
#         xterm -title "Gazebo Terminal" -e "gazebo --verbose $DEPL_GAZEBO_FILES/worlds/pioneerOffice.world || bash; sleep 5" &


;;

post-start)
	# first, trigger hooks as delivered from component ...
	bash startstop-hooks-component-SmartGazeboBaseServer.sh post-start
	
	# ...then call user/deployment specific hook:
	echo "Triggering post-start hooks ..."
;;

pre-stop)
	# first, trigger hooks as delivered from component ...
	bash startstop-hooks-component-SmartGazeboBaseServer.sh pre-stop
	
	# ...then call user/deployment specific hook:
	echo "Triggering pre-stop hooks ..."
;;

post-stop)
	# first, trigger hooks as delivered from component ...
	bash startstop-hooks-component-SmartGazeboBaseServer.sh post-stop
	
	# ...then call user/deployment specific hook:
	echo "Triggering post-stop hooks ..."

	killall gzserver
	killall gzclient
;;

*)
	echo "ERROR in $0: no such hook '$1'. Usage: $0 pre-start|post-start|pre-stop|post-stop"
;;

esac

